model:
  llm: ycchen/breeze-7b-instruct-v1_0
  embeddings_model: aspire/acge_text_embedding
database:
  collection: datav1
  internal_host: http://qdrant:6333
  external_host: http://localhost:6333
backend:
  host: http://localhost:8080
